name: Test, Build and Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided.
  build:
    # Name the Job
    name: 'Job: Build'
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: npm -v
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: npm run generate-badges
      - name: Generate coverage badges
        run: |
          git fetch
          git add .
          git stash
          git checkout badges
          rm -rf badges
          git add .
          git stash pop
          git add badges/*
          if ! git diff-index --quiet HEAD; then
            git config --global user.name '  Hub Actions'
            git config --global user.email 'actions@github.com'
            git commit -am "Generate coverage badges" --author="Author <actions@github.com>"
            git push
          else
            echo "Working tree clean. Nothing to commit."
          fi
