name: Test, Build and Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided.
  build:
    # Name the Job
    name: 'Job: Build'
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: git fetch
      - run: npm run generate-badges
      - run: git add .
      - run: git stash
      - run: git checkout badges
      - run: rm -rf badges
      - run: git add .
      - run: git stash pop
      - name: Generate coverage badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate coverage badges
          branch: badges
          file_pattern: badges/*
          commit_author: Author <actions@github.com>
